# Generated by Django 6.1.2 on 2026-10-07 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('source_record_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=20)),
                ('source_system', models.CharField(max_length=50)),
                ('record_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('target', models.FloatField(null=True)),
                ('target_unit', models.CharField(max_length=20)),
                ('reported_actual', models.FloatField(null=True)),
                ('reported_progress_pct', models.FloatField(null=True)),
                ('reported_status', models.CharField(max_length=30)),
                ('last_reported_update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('update_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('source_type', models.CharField(max_length=30)),
                ('source_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetrics',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metrics', serialize=False, to='monitor.project')),
                ('as_of', models.DateTimeField()),
                ('computed_pct', models.FloatField(null=True)),
                ('observed_actual', models.FloatField(null=True)),
                ('observed_at', models.DateTimeField(null=True)),
                ('observed_source_id', models.CharField(max_length=40, null=True)),
                ('observed_pct', models.FloatField(null=True)),
                ('days_remaining', models.IntegerField(null=True)),
                ('historical_rate', models.FloatField(null=True)),
                ('required_rate', models.FloatField(null=True)),
                ('pace_ratio', models.FloatField(null=True)),
                ('stated_capacity', models.FloatField(null=True)),
                ('last_activity_at', models.DateTimeField(null=True)),
                ('attention', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=40)),
                ('severity', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('explanation', models.TextField()),
                ('verify', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('evidence', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='monitor.project')),
            ],
        ),
    ]
