# Generated by Django 6.1.2 on 2026-10-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectmetrics',
            name='forecast_delay_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projectmetrics',
            name='forecast_finish',
            field=models.DateTimeField(null=True),
        ),
    ]
